# Generated by Django 3.0.1 on 2019-12-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authror',
            new_name='author',
        ),
    ]
